// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const GetDashboardReportByDateRange = `-- name: GetDashboardReportByDateRange :one
SELECT 
    COUNT(d.id) as total_waqfs,
    COALESCE(SUM(d.amount), 0) as total_amount,
    COUNT(DISTINCT d.project_id) as total_projects
FROM donations d
JOIN projects p ON d.project_id = p.id
WHERE p.is_active = true 
AND d.payment_status = 'Completed'
AND d.created_date >= $1 
AND d.created_date <= $2
`

type GetDashboardReportByDateRangeParams struct {
	CreatedDate   time.Time `json:"created_date"`
	CreatedDate_2 time.Time `json:"created_date_2"`
}

type GetDashboardReportByDateRangeRow struct {
	TotalWaqfs    int64       `json:"total_waqfs"`
	TotalAmount   interface{} `json:"total_amount"`
	TotalProjects int64       `json:"total_projects"`
}

func (q *Queries) GetDashboardReportByDateRange(ctx context.Context, arg *GetDashboardReportByDateRangeParams) (*GetDashboardReportByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, GetDashboardReportByDateRange, arg.CreatedDate, arg.CreatedDate_2)
	var i GetDashboardReportByDateRangeRow
	err := row.Scan(&i.TotalWaqfs, &i.TotalAmount, &i.TotalProjects)
	return &i, err
}

const GetDonationTypesReport = `-- name: GetDonationTypesReport :many
SELECT 
    d.donation_type,
    COUNT(d.id) as total_donations,
    COALESCE(SUM(d.amount), 0) as total_amount
FROM donations d
JOIN projects p ON d.project_id = p.id
WHERE d.payment_status = 'Completed' AND p.is_active = true
GROUP BY d.donation_type
ORDER BY total_amount DESC
`

type GetDonationTypesReportRow struct {
	DonationType   *string     `json:"donation_type"`
	TotalDonations int64       `json:"total_donations"`
	TotalAmount    interface{} `json:"total_amount"`
}

func (q *Queries) GetDonationTypesReport(ctx context.Context) ([]*GetDonationTypesReportRow, error) {
	rows, err := q.db.Query(ctx, GetDonationTypesReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetDonationTypesReportRow{}
	for rows.Next() {
		var i GetDonationTypesReportRow
		if err := rows.Scan(&i.DonationType, &i.TotalDonations, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetMonthlyDonationTrend = `-- name: GetMonthlyDonationTrend :many
SELECT 
    DATE_TRUNC('month', d.created_date) as month,
    COUNT(d.id) as total_waqfs,
    COALESCE(SUM(d.amount), 0) as total_amount
FROM donations d
JOIN projects p ON d.project_id = p.id
WHERE p.is_active = true 
AND d.payment_status = 'Completed'
AND d.created_date >= $1 
AND d.created_date <= $2
GROUP BY DATE_TRUNC('month', d.created_date)
ORDER BY month
`

type GetMonthlyDonationTrendParams struct {
	CreatedDate   time.Time `json:"created_date"`
	CreatedDate_2 time.Time `json:"created_date_2"`
}

type GetMonthlyDonationTrendRow struct {
	Month       pgtype.Interval `json:"month"`
	TotalWaqfs  int64           `json:"total_waqfs"`
	TotalAmount interface{}     `json:"total_amount"`
}

func (q *Queries) GetMonthlyDonationTrend(ctx context.Context, arg *GetMonthlyDonationTrendParams) ([]*GetMonthlyDonationTrendRow, error) {
	rows, err := q.db.Query(ctx, GetMonthlyDonationTrend, arg.CreatedDate, arg.CreatedDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMonthlyDonationTrendRow{}
	for rows.Next() {
		var i GetMonthlyDonationTrendRow
		if err := rows.Scan(&i.Month, &i.TotalWaqfs, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOrganizationDashboardReport = `-- name: GetOrganizationDashboardReport :one
SELECT 
    COUNT(DISTINCT p.id) as total_projects,
    COUNT(d.id) as total_waqfs,
    COALESCE(SUM(d.amount), 0) as total_donations
FROM organizations o
LEFT JOIN projects p ON o.id = p.organization_id AND p.is_active = true
LEFT JOIN donations d ON p.id = d.project_id AND d.payment_status = 'Completed'
WHERE o.id = $1 AND o.is_active = true
`

type GetOrganizationDashboardReportRow struct {
	TotalProjects  int64       `json:"total_projects"`
	TotalWaqfs     int64       `json:"total_waqfs"`
	TotalDonations interface{} `json:"total_donations"`
}

func (q *Queries) GetOrganizationDashboardReport(ctx context.Context, id uuid.UUID) (*GetOrganizationDashboardReportRow, error) {
	row := q.db.QueryRow(ctx, GetOrganizationDashboardReport, id)
	var i GetOrganizationDashboardReportRow
	err := row.Scan(&i.TotalProjects, &i.TotalWaqfs, &i.TotalDonations)
	return &i, err
}

const GetTotalDonationsReport = `-- name: GetTotalDonationsReport :one
SELECT 
    COUNT(d.id) as total_waqfs,
    COALESCE(SUM(d.amount), 0) as total_amount,
    COUNT(DISTINCT d.project_id) as total_projects
FROM donations d
JOIN projects p ON d.project_id = p.id
WHERE p.is_active = true AND d.payment_status = 'Completed'
`

type GetTotalDonationsReportRow struct {
	TotalWaqfs    int64       `json:"total_waqfs"`
	TotalAmount   interface{} `json:"total_amount"`
	TotalProjects int64       `json:"total_projects"`
}

func (q *Queries) GetTotalDonationsReport(ctx context.Context) (*GetTotalDonationsReportRow, error) {
	row := q.db.QueryRow(ctx, GetTotalDonationsReport)
	var i GetTotalDonationsReportRow
	err := row.Scan(&i.TotalWaqfs, &i.TotalAmount, &i.TotalProjects)
	return &i, err
}
