// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const CreateOrganizationRequest = `-- name: CreateOrganizationRequest :one
INSERT INTO organization_requests (
    name,
    phone,
    cr,
    description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, phone, cr, description, status, created_date, modified_date
`

type CreateOrganizationRequestParams struct {
	Name        string  `json:"name"`
	Phone       string  `json:"phone"`
	Cr          string  `json:"cr"`
	Description *string `json:"description"`
}

func (q *Queries) CreateOrganizationRequest(ctx context.Context, arg *CreateOrganizationRequestParams) (*OrganizationRequest, error) {
	row := q.db.QueryRow(ctx, CreateOrganizationRequest,
		arg.Name,
		arg.Phone,
		arg.Cr,
		arg.Description,
	)
	var i OrganizationRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cr,
		&i.Description,
		&i.Status,
		&i.CreatedDate,
		&i.ModifiedDate,
	)
	return &i, err
}

const CreateOrganizationRequestDocument = `-- name: CreateOrganizationRequestDocument :one
INSERT INTO organization_request_documents (
    request_id,
    document_path
) VALUES (
    $1, $2
) RETURNING id, request_id, document_path, created_date
`

type CreateOrganizationRequestDocumentParams struct {
	RequestID    pgtype.UUID `json:"request_id"`
	DocumentPath string      `json:"document_path"`
}

func (q *Queries) CreateOrganizationRequestDocument(ctx context.Context, arg *CreateOrganizationRequestDocumentParams) (*OrganizationRequestDocument, error) {
	row := q.db.QueryRow(ctx, CreateOrganizationRequestDocument, arg.RequestID, arg.DocumentPath)
	var i OrganizationRequestDocument
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DocumentPath,
		&i.CreatedDate,
	)
	return &i, err
}

const DeleteOrganizationRequestDocument = `-- name: DeleteOrganizationRequestDocument :exec
DELETE FROM organization_request_documents
WHERE id = $1
`

func (q *Queries) DeleteOrganizationRequestDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteOrganizationRequestDocument, id)
	return err
}

const GetOrganizationRequestByID = `-- name: GetOrganizationRequestByID :one
SELECT id, name, phone, cr, description, status, created_date, modified_date FROM organization_requests
WHERE id = $1
`

func (q *Queries) GetOrganizationRequestByID(ctx context.Context, id uuid.UUID) (*OrganizationRequest, error) {
	row := q.db.QueryRow(ctx, GetOrganizationRequestByID, id)
	var i OrganizationRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cr,
		&i.Description,
		&i.Status,
		&i.CreatedDate,
		&i.ModifiedDate,
	)
	return &i, err
}

const GetOrganizationRequestDocuments = `-- name: GetOrganizationRequestDocuments :many
SELECT id, request_id, document_path, created_date FROM organization_request_documents
WHERE request_id = $1
ORDER BY created_date
`

func (q *Queries) GetOrganizationRequestDocuments(ctx context.Context, requestID pgtype.UUID) ([]*OrganizationRequestDocument, error) {
	rows, err := q.db.Query(ctx, GetOrganizationRequestDocuments, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrganizationRequestDocument{}
	for rows.Next() {
		var i OrganizationRequestDocument
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.DocumentPath,
			&i.CreatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOrganizationRequests = `-- name: ListOrganizationRequests :many
SELECT id, name, phone, cr, description, status, created_date, modified_date FROM organization_requests
ORDER BY created_date DESC
`

func (q *Queries) ListOrganizationRequests(ctx context.Context) ([]*OrganizationRequest, error) {
	rows, err := q.db.Query(ctx, ListOrganizationRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrganizationRequest{}
	for rows.Next() {
		var i OrganizationRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Cr,
			&i.Description,
			&i.Status,
			&i.CreatedDate,
			&i.ModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOrganizationRequestsByStatus = `-- name: ListOrganizationRequestsByStatus :many
SELECT id, name, phone, cr, description, status, created_date, modified_date FROM organization_requests
WHERE status = $1
ORDER BY created_date DESC
`

func (q *Queries) ListOrganizationRequestsByStatus(ctx context.Context, status NullOrganizationRequestStatus) ([]*OrganizationRequest, error) {
	rows, err := q.db.Query(ctx, ListOrganizationRequestsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*OrganizationRequest{}
	for rows.Next() {
		var i OrganizationRequest
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Cr,
			&i.Description,
			&i.Status,
			&i.CreatedDate,
			&i.ModifiedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateOrganizationRequestStatus = `-- name: UpdateOrganizationRequestStatus :one
UPDATE organization_requests
SET status = $1, modified_date = NOW()
WHERE id = $2
RETURNING id, name, phone, cr, description, status, created_date, modified_date
`

type UpdateOrganizationRequestStatusParams struct {
	Status NullOrganizationRequestStatus `json:"status"`
	ID     uuid.UUID                     `json:"id"`
}

func (q *Queries) UpdateOrganizationRequestStatus(ctx context.Context, arg *UpdateOrganizationRequestStatusParams) (*OrganizationRequest, error) {
	row := q.db.QueryRow(ctx, UpdateOrganizationRequestStatus, arg.Status, arg.ID)
	var i OrganizationRequest
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Cr,
		&i.Description,
		&i.Status,
		&i.CreatedDate,
		&i.ModifiedDate,
	)
	return &i, err
}
