// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDonation(ctx context.Context, arg *CreateDonationParams) (*Donation, error)
	CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*Organization, error)
	CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	GetDashboardReportByDateRange(ctx context.Context, arg *GetDashboardReportByDateRangeParams) (*GetDashboardReportByDateRangeRow, error)
	GetDonationByID(ctx context.Context, id uuid.UUID) (*Donation, error)
	GetDonationTypesReport(ctx context.Context) ([]*GetDonationTypesReportRow, error)
	GetDonationsByOrganizationID(ctx context.Context, organizationID pgtype.UUID) ([]*Donation, error)
	GetDonationsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]*Donation, error)
	GetMonthlyDonationTrend(ctx context.Context, arg *GetMonthlyDonationTrendParams) ([]*GetMonthlyDonationTrendRow, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (*Organization, error)
	GetOrganizationDashboardReport(ctx context.Context, id uuid.UUID) (*GetOrganizationDashboardReportRow, error)
	GetOrganizationDonationStats(ctx context.Context, organizationID pgtype.UUID) (*GetOrganizationDonationStatsRow, error)
	GetOrganizationDonorsCount(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetOrganizationProjectCount(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetOrganizationProjectsTotalValue(ctx context.Context, organizationID pgtype.UUID) (interface{}, error)
	GetOrganizationTotalDonations(ctx context.Context, organizationID pgtype.UUID) (interface{}, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (*Project, error)
	GetProjectCountByOrganizationID(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetProjectDonationStats(ctx context.Context, projectID pgtype.UUID) (*GetProjectDonationStatsRow, error)
	GetProjectFinancialStatus(ctx context.Context, id uuid.UUID) (*GetProjectFinancialStatusRow, error)
	GetProjectsByOrganizationID(ctx context.Context, organizationID pgtype.UUID) ([]*Project, error)
	GetTopDonorsByOrganization(ctx context.Context, arg *GetTopDonorsByOrganizationParams) ([]*GetTopDonorsByOrganizationRow, error)
	GetTopDonorsByProject(ctx context.Context, arg *GetTopDonorsByProjectParams) ([]*GetTopDonorsByProjectRow, error)
	GetTotalDonationsReport(ctx context.Context) (*GetTotalDonationsReportRow, error)
	ListOrganizations(ctx context.Context) ([]*Organization, error)
	ListProjects(ctx context.Context) ([]*Project, error)
	UpdateDonationPaymentStatus(ctx context.Context, arg *UpdateDonationPaymentStatusParams) (*Donation, error)
	UpdateOrganization(ctx context.Context, arg *UpdateOrganizationParams) (*Organization, error)
	UpdateProject(ctx context.Context, arg *UpdateProjectParams) (*Project, error)
}

var _ Querier = (*Queries)(nil)
