// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg *CreateOrganizationParams) (*Organization, error)
	CreatePaymentConfiguration(ctx context.Context, arg *CreatePaymentConfigurationParams) (*PaymentConfiguration, error)
	CreatePaymentTrack(ctx context.Context, arg *CreatePaymentTrackParams) (*PaymentTrack, error)
	CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error)
	CreateWaqf(ctx context.Context, arg *CreateWaqfParams) (*Waqf, error)
	CreateWaqfType(ctx context.Context, arg *CreateWaqfTypeParams) (*WaqfType, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteWaqfType(ctx context.Context, id uuid.UUID) error
	GetDashboardReportByDateRange(ctx context.Context, arg *GetDashboardReportByDateRangeParams) (*GetDashboardReportByDateRangeRow, error)
	GetMonthlyDonationTrend(ctx context.Context, arg *GetMonthlyDonationTrendParams) ([]*GetMonthlyDonationTrendRow, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (*Organization, error)
	GetOrganizationDashboardReport(ctx context.Context, id uuid.UUID) (*GetOrganizationDashboardReportRow, error)
	GetOrganizationDonorsCount(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetOrganizationProjectCount(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetOrganizationProjectsTotalValue(ctx context.Context, organizationID pgtype.UUID) (interface{}, error)
	GetOrganizationTotalDonations(ctx context.Context, organizationID pgtype.UUID) (interface{}, error)
	GetPaymentConfigurationByOrganizationID(ctx context.Context, organizationID pgtype.UUID) (*PaymentConfiguration, error)
	GetPaymentTrackByID(ctx context.Context, id uuid.UUID) (*PaymentTrack, error)
	GetPaymentTrackByTrackID(ctx context.Context, trackID string) (*PaymentTrack, error)
	GetPaymentsByWaqfID(ctx context.Context, waqfID pgtype.UUID) ([]*PaymentTrack, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (*Project, error)
	GetProjectCountByOrganizationID(ctx context.Context, organizationID pgtype.UUID) (int64, error)
	GetProjectFinancialStatus(ctx context.Context, id uuid.UUID) (*GetProjectFinancialStatusRow, error)
	GetProjectsByOrganizationID(ctx context.Context, organizationID pgtype.UUID) ([]*Project, error)
	GetTotalDonationsReport(ctx context.Context) (*GetTotalDonationsReportRow, error)
	GetWaqfByID(ctx context.Context, id uuid.UUID) (*Waqf, error)
	GetWaqfTypeByID(ctx context.Context, id uuid.UUID) (*WaqfType, error)
	GetWaqfTypeDonatedReport(ctx context.Context) ([]*GetWaqfTypeDonatedReportRow, error)
	GetWaqfsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]*GetWaqfsByProjectIDRow, error)
	ListOrganizations(ctx context.Context) ([]*Organization, error)
	ListPaymentTracks(ctx context.Context) ([]*ListPaymentTracksRow, error)
	ListProjects(ctx context.Context) ([]*Project, error)
	ListWaqfTypes(ctx context.Context) ([]*WaqfType, error)
	ListWaqfs(ctx context.Context) ([]*ListWaqfsRow, error)
	UpdateOrganization(ctx context.Context, arg *UpdateOrganizationParams) (*Organization, error)
	UpdatePaymentConfiguration(ctx context.Context, arg *UpdatePaymentConfigurationParams) (*PaymentConfiguration, error)
	UpdatePaymentStatus(ctx context.Context, arg *UpdatePaymentStatusParams) (*PaymentTrack, error)
	UpdateProject(ctx context.Context, arg *UpdateProjectParams) (*Project, error)
	UpdateWaqfType(ctx context.Context, arg *UpdateWaqfTypeParams) (*WaqfType, error)
}

var _ Querier = (*Queries)(nil)
